# Generated by Django 4.2.6 on 2023-12-09 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudyingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('birthday_date', models.DateField()),
                ('town', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('favorite_num', models.ManyToManyField(to='user_info.numeral')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.studyingprogram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
