# Generated by Django 4.2.6 on 2023-12-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='status',
        ),
    ]
