# Generated by Django 4.2.6 on 2023-12-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_remove_userinfo_department_remove_userinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='birthday_date',
        ),
    ]
