# Generated by Django 4.2.6 on 2023-12-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_remove_userinfo_birthday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.studyingprogram'),
        ),
    ]
