# Generated by Django 4.2.6 on 2023-12-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='image',
        ),
    ]
