# Generated by Django 4.2.6 on 2023-12-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_remove_yourmodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
