# Generated by Django 4.2.6 on 2023-12-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_alter_userinfo_program_alter_userinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='subscribed_chanel',
            field=models.ManyToManyField(to='user_info.chanel'),
        ),
    ]
