# Generated by Django 4.2.6 on 2023-12-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0009_chanel_userinfo_subscribed_chanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='subscribed_chanel',
        ),
        migrations.DeleteModel(
            name='Chanel',
        ),
    ]
