# Generated by Django 4.2.6 on 2023-12-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0012_remove_userinfo_subscribed_chanel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_subscribed',
        ),
    ]
