# Generated by Django 4.2.6 on 2023-12-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0013_remove_userinfo_is_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
    ]
