# Generated by Django 4.2.6 on 2023-12-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0018_userinfo_third_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
    ]
