# Generated by Django 4.2.6 on 2024-01-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0019_remove_quiz_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='language',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='good_program',
            new_name='form',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='favorite_picture',
        ),
        migrations.AddField(
            model_name='quiz',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
